acara/urls.py
from django.urls import path
from .views import *

app_name = 'acara'
urlpatterns = [
    path('', acara, name="list-acara"),
    path('sortasc/', sortbyacaraASC, name="sort-asc"),
    path('sortdesc/', sortbyacaraDESC, name="sort-desc"),
    path('petugas/register/', register_acara, name="admin-register-acara"),
    path('petugas/update/', update_acara, name="admin-update-acara"),
]

bikesharing/urls.py
from django.contrib import admin
from django.urls import path, include
from registration.views import registration

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('petugas/', include('petugas.urls', namespace='petugas')),
    path('registration/', include('registration.urls', namespace='auth')),
    path('voucher/', include('voucher.urls', namespace='voucher')),
    path('stasiun/', include('stasiun.urls', namespace='stasiun')),
    path('acara/', include('acara.urls', namespace='acara')),
    path('sepeda/', include('sepeda.urls', namespace='sepeda')),
    path('transaksi/', include('transaksi.urls')),
    path('laporan/', include('laporan.urls', namespace='laporan')),
    path('', include('peminjaman.urls', namespace='peminjaman')),
]

acara/models.py
from django.db import models

# Create your models here.

acara/forms.py
from django import forms
from django.db import connection


def list_stasiun():
    with connection.cursor() as cursor:
        cursor.execute(
            'SELECT nama from stasiun'
        )
        row = cursor.fetchall()
    return row


class orderFilter(forms.Form):
    list_stasiun = forms.ChoiceField(required=False, label="", widget=forms.Select(
        attrs={'class': 'form-control'}, choices=list_stasiun()))
    judul = forms.CharField(label="", required=True, max_length=20,
                            widget=forms.TextInput(
                                attrs={'class': 'form-control'}))
    deskripsi = forms.CharField(label="", required=False, max_length=200,
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control'}))
    isFree = forms.ChoiceField(required=False, label="Filter Stasiun", widget=forms.Select(
        attrs={'class': 'form-control'}), choices=(('Ya', 'Ya'), ('Tidak', 'Tidak')))
    tgl_mulai = forms.DateField(label="", required=True,
                                widget=forms.DateInput(attrs={'class': 'form-control'}))
    tgl_selesai = forms.DateField(label="", required=True,
                                  widget=forms.DateInput(attrs={'class': 'form-control'}))

acara/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import messages
from sepeda.models import *
from .forms import *
from registration.check import required_login
from django.core.paginator import Paginator

content = {}


# Create your views here.

@required_login
def acara(request):
    list_acara = list(Acara.objects.raw(
        'SELECT * FROM ACARA NATURAL JOIN ACARA_STASIUN NATURAL JOIN STASIUN'))
    pagination = Paginator(list_acara, 6)
    page = request.GET.get('page')
    items = pagination.get_page(page)
    content['items'] = items
    return render(request, 'acara/acara.html', content)


@required_login
def sortbyacaraASC(request):
    list_acara = list(Acara.objects.raw(
        'SELECT * FROM ACARA NATURAL JOIN ACARA_STASIUN NATURAL JOIN STASIUN ORDER BY judul ASC'))
    pagination = Paginator(list_acara, 6)
    page = request.GET.get('page')
    items = pagination.get_page(page)
    content['items'] = items
    return render(request, 'acara/acara.html', content)


@required_login
def sortbyacaraDESC(request):
    list_acara = list(Acara.objects.raw(
        'SELECT * FROM ACARA NATURAL JOIN ACARA_STASIUN NATURAL JOIN STASIUN ORDER BY judul DESC'))
    pagination = Paginator(list_acara, 6)
    page = request.GET.get('page')
    items = pagination.get_page(page)
    content['items'] = items
    return render(request, 'acara/acara.html', content)


def register_acara(request):
    return render(request, 'acara/register-acara.html')


def update_acara(request):
    return render(request, 'acara/update-acara.html')

acara/templates/acara/acara.html
{% extends 'base/base.html' %}
{% load static %}

{% block extracss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style-table.css' %}" />
{% endblock %}

{% block extrascript %}
<script src="{% static 'stasiun/js/index.js' %}"></script>
{% endblock %}

{% block content %}
<div class="content-info d-flex align-items-center justify-content-between">
    <div class="d-flex align-items-center justify-content-between">
        <h5><b>Daftar Acara</b></h5>
        {% if request.session.role == 'Petugas' %}
        <a href="{% url 'acara:admin-register-acara' %}">
            <button class="btn add-btn-secondary">TAMBAH</button>
        </a>
        {% endif %}
    </div>
    <div class="filter-btn-group d-flex">
        <div class="dropdown">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                <i class="fas fa-filter"></i> Filter
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Link 1</a>
                <a class="dropdown-item" href="#">Link 2</a>
                <a class="dropdown-item" href="#">Link 3</a>
            </div>
        </div>
        <div class="dropdown">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                <i class="fas fa-sort-amount-down"></i>
                Sort
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'acara:list-acara' %}">default</a>
                <a class="dropdown-item" href="{% url 'acara:sort-asc' %}">A to Z</a>
                <a class="dropdown-item" href="{% url 'acara:sort-desc' %}">Z to A</a>
            </div>
        </div>
    </div>
</div>
<table class="table table-striped table-hover table-responsive-lg">
    <thead class="thead-light" align="center">
        <tr>
            <th>Judul</th>
            <th>Deskripsi</th>
            <th>Gratis</th>
            <th>Tanggal Mulai</th>
            <th>Tanggal Selesai</th>
            <th>Stasiun</th>
            {% if request.session.role == 'Petugas' %}
            <th>Action</th>
            {% endif %}

        </tr>
    </thead>
    <tbody align="center">
        {% for data in items %}
        <tr>
            <td>{{ data.judul }}</td>
            <td>{{ data.deskripsi }}</td>
            {% if data.is_free %}
            <td>Yes</td>
            {% else %}
            <td>No</td>
            {% endif %}
            <td>{{ data.tgl_mulai }}</td>
            <td>{{ data.tgl_akhir }}</td>
            <td>{{ data.nama }}</td>
            {% if request.session.role == 'Petugas' %}
            <td class="d-flex align-items-center justify-content-center"><a
                    href="{% url 'acara:admin-update-acara' %}"><i class="fas fa-pen"></i></a><a id="delete-1"
                    onclick="popUpModal()"><i class="fas fa-trash-alt"></i></a></td>
            {% endif %}

        </tr>
        {% endfor %}
    </tbody>
</table>
<!-- The Modal -->
<div class="modal fade" id="myModal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <!-- Modal body -->
            <div class="modal-body">
                Apakah benar ingin menghapus acara tersebut?
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">TIDAK</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">YA</button>
            </div>
        </div>
    </div>
</div>
{% include 'partial/pagination.html' %}
{% endblock %}

acara/templates/acara/register-acara.html
{% extends 'base/base.html' %}
{% load static %}

{% block extracss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style-table.css' %}" />
{% endblock %}

{% block content %}
<div class="content-info d-flex align-items-center justify-content-between">
    <h5><b>Tambah Acara</b></h5>
</div>
<form class="form">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="JUDUL ACARA">
    </div>
    <div class="form-group">
        <textarea class="form-control" rows="10" cols="90" placeholder="DESKRIPSI"></textarea>
    </div>
    <div class="form-group divided-form d-flex justify-content-between">
        <div class="dropdown">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                FREE
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Ya</a>
                <a class="dropdown-item" href="#">Tidak</a>
            </div>
        </div>
        <input type="text" class="form-control" placeholder="TANGGAL MULAI" onfocus="(this.type = 'date')">
        <input type="text" class="form-control" placeholder="TANGGAL SELESAI" onfocus="(this.type = 'date')">
    </div>
    <div class="form-group divided-form d-flex justify-content-between">
        <div class="dropdown">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                NAMA STASIUN (MULTIVALUES)
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Link 1</a>
                <a class="dropdown-item" href="#">Link 2</a>
                <a class="dropdown-item" href="#">Link 3</a>
            </div>
        </div>
        <div class="form-group d-flex justify-content-end">
            <button type="submit" class="btn btn-secondary btn-submit">SUBMIT</button>
        </div>


</form>
{% endblock %}

acara/templates/acara/update-acara.html
{% extends 'base/base.html' %}
{% load static %}

{% block extracss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style-table.css' %}" />
{% endblock %}

{% block content %}
<div class="content-info d-flex align-items-center justify-content-between">
    <h5><b>Update Acara</b></h5>
</div>

<form class="form">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="ABC">
    </div>
    <div class="form-group">
        <textarea class="form-control" rows="10" cols="90" placeholder="Lorem Ipsum"></textarea>
    </div>
    <div class="form-group divided-form d-flex justify-content-between">
        <div class="dropdown">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                Ya
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Ya</a>
                <a class="dropdown-item" href="#">Tidak</a>
            </div>
        </div>
        <input type="text" class="form-control" placeholder="23/06/19" onfocus="(this.type = 'date')">
        <input type="text" class="form-control" placeholder="24/06/19" onfocus="(this.type = 'date')">
    </div>
    <div class="form-group divided-form d-flex justify-content-between">
        <div class="dropdown">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                Duri
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Duri</a>
                <a class="dropdown-item" href="#">Duren Kalibata</a>
                <a class="dropdown-item" href="#">Lenteng Agung</a>
            </div>
        </div>
        <div class="form-group d-flex justify-content-end">
            <button type="submit" class="btn btn-secondary btn-submit">SUBMIT</button>
        </div>
    </div>
</form>
{% endblock %}