acara/urls.py
from django.urls import path
from .views import *

app_name = 'acara'
urlpatterns = [
    path('', acara, name="list-acara"),
    path('sortasc/', sortbyacaraASC, name="sort-asc"),
    path('sortdesc/', sortbyacaraDESC, name="sort-desc"),
    path('petugas/register/', register_acara, name="admin-register-acara"),
    path('petugas/update/', update_acara, name="admin-update-acara"),
]

bikesharing/urls.py
from django.contrib import admin
from django.urls import path, include
from registration.views import registration

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('petugas/', include('petugas.urls', namespace='petugas')),
    path('registration/', include('registration.urls', namespace='auth')),
    path('voucher/', include('voucher.urls', namespace='voucher')),
    path('stasiun/', include('stasiun.urls', namespace='stasiun')),
    path('acara/', include('acara.urls', namespace='acara')),
    path('sepeda/', include('sepeda.urls', namespace='sepeda')),
    path('transaksi/', include('transaksi.urls')),
    path('laporan/', include('laporan.urls', namespace='laporan')),
    path('', include('peminjaman.urls', namespace='peminjaman')),
]

peminjaman/urls.py
from django.urls import path
from .views import *

app_name = 'peminjaman'
urlpatterns = [
    path('', peminjaman, name="list-peminjaman"),
    path('register/', register_peminjaman, name="register-peminjaman"),
]

sepeda/urls.py
from django.urls import path
from .views import *

app_name = 'sepeda'
urlpatterns = [
    path('', sepeda, name="list-sepeda"),
    path('sortasc/', sortbysepedaASC, name="sort-asc"),
    path('sortdesc/', sortbysepedaDESC, name="sort-desc"),
    path('register/', register_sepeda, name="register-sepeda"),
    path('update/<str:nomor>/', update_sepeda, name="update-sepeda"),
]

sepeda/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Acara(models.Model):
    id_acara = models.CharField(primary_key=True, max_length=10)
    judul = models.CharField(max_length=100)
    deskripsi = models.TextField(blank=True, null=True)
    tgl_mulai = models.DateField()
    tgl_akhir = models.DateField()
    is_free = models.BooleanField()

    class Meta:
        managed = False
        db_table = 'acara'


class AcaraStasiun(models.Model):
    id_acara = models.ForeignKey(Acara, models.DO_NOTHING, db_column='id_acara')
    id_stasiun = models.ForeignKey('Stasiun', models.DO_NOTHING, db_column='id_stasiun', primary_key=True)

    class Meta:
        managed = False
        db_table = 'acara_stasiun'
        unique_together = (('id_stasiun', 'id_acara'),)


class Anggota(models.Model):
    no_kartu = models.CharField(primary_key=True, max_length=10)
    saldo = models.FloatField(blank=True, null=True)
    points = models.IntegerField(blank=True, null=True)
    ktp = models.ForeignKey('Person', models.DO_NOTHING, db_column='ktp')

    class Meta:
        managed = False
        db_table = 'anggota'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Laporan(models.Model):
    id_laporan = models.CharField(primary_key=True, max_length=10)
    no_kartu_anggota = models.ForeignKey('Peminjaman', models.DO_NOTHING, db_column='no_kartu_anggota')
    datetime_pinjam = models.DateTimeField()
    nomor_sepeda = models.CharField(max_length=10)
    id_stasiun = models.CharField(max_length=10)
    status = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'laporan'
        unique_together = (('id_laporan', 'no_kartu_anggota', 'datetime_pinjam', 'nomor_sepeda', 'id_stasiun'),)


class Peminjaman(models.Model):
    no_kartu_anggota = models.ForeignKey(Anggota, models.DO_NOTHING, db_column='no_kartu_anggota', primary_key=True)
    datetime_pinjam = models.DateTimeField()
    nomor_sepeda = models.ForeignKey('Sepeda', models.DO_NOTHING, db_column='nomor_sepeda')
    id_stasiun = models.ForeignKey('Stasiun', models.DO_NOTHING, db_column='id_stasiun')
    datetime_kembali = models.DateTimeField(blank=True, null=True)
    biaya = models.FloatField(blank=True, null=True)
    denda = models.FloatField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'peminjaman'
        unique_together = (('no_kartu_anggota', 'datetime_pinjam', 'nomor_sepeda', 'id_stasiun'),)


class Penugasan(models.Model):
    ktp = models.ForeignKey('Petugas', models.DO_NOTHING, db_column='ktp', primary_key=True)
    start_datetime = models.DateTimeField()
    id_stasiun = models.ForeignKey('Stasiun', models.DO_NOTHING, db_column='id_stasiun')
    end_datetime = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'penugasan'
        unique_together = (('ktp', 'start_datetime', 'id_stasiun'),)


class Person(models.Model):
    ktp = models.CharField(primary_key=True, max_length=20)
    email = models.CharField(unique=True, max_length=50)
    nama = models.CharField(max_length=50)
    alamat = models.TextField(blank=True, null=True)
    tgl_lahir = models.DateField()
    no_telp = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'person'


class Petugas(models.Model):
    ktp = models.ForeignKey(Person, models.DO_NOTHING, db_column='ktp', primary_key=True)
    gaji = models.FloatField()

    class Meta:
        managed = False
        db_table = 'petugas'


class Sepeda(models.Model):
    nomor = models.CharField(primary_key=True, max_length=10)
    merk = models.CharField(max_length=10)
    jenis = models.CharField(max_length=50)
    status = models.BooleanField()
    id_stasiun = models.ForeignKey('Stasiun', models.DO_NOTHING, db_column='id_stasiun')
    no_kartu_penyumbang = models.ForeignKey(Anggota, models.DO_NOTHING, db_column='no_kartu_penyumbang', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'sepeda'


class Stasiun(models.Model):
    id_stasiun = models.CharField(primary_key=True, max_length=10)
    alamat = models.TextField()
    lat = models.FloatField(blank=True, null=True)
    long = models.FloatField(blank=True, null=True)
    nama = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'stasiun'


class Transaksi(models.Model):
    no_kartu_anggota = models.ForeignKey(Anggota, models.DO_NOTHING, db_column='no_kartu_anggota', primary_key=True)
    date_time = models.DateTimeField()
    jenis = models.CharField(max_length=20)
    nominal = models.FloatField()

    class Meta:
        managed = False
        db_table = 'transaksi'
        unique_together = (('no_kartu_anggota', 'date_time'),)


class TransaksiKhususPeminjaman(models.Model):
    no_kartu_anggota = models.ForeignKey(Transaksi, models.DO_NOTHING, db_column='no_kartu_anggota', primary_key=True)
    date_time = models.DateTimeField()
    no_kartu_peminjam = models.ForeignKey(Peminjaman, models.DO_NOTHING, db_column='no_kartu_peminjam', blank=True, null=True)
    datetime_pinjam = models.DateTimeField(blank=True, null=True)
    no_sepeda = models.CharField(max_length=10, blank=True, null=True)
    id_stasiun = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'transaksi_khusus_peminjaman'
        unique_together = (('no_kartu_anggota', 'date_time'),)


class Voucher(models.Model):
    id_voucher = models.CharField(primary_key=True, max_length=10)
    nama = models.CharField(max_length=255)
    kategori = models.CharField(max_length=255)
    nilai_poin = models.FloatField()
    deskripsi = models.TextField(blank=True, null=True)
    no_kartu_anggota = models.ForeignKey(Anggota, models.DO_NOTHING, db_column='no_kartu_anggota', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'voucher'

sepeda/forms.py
from django import forms
from sepeda.models import *


def render_choices():
    choices = []
    query = list(Stasiun.objects.raw('SELECT * FROM STASIUN'))
    for i in query:
        choices.append([i.nama, i.nama])
    return choices


class SepedaForm(forms.Form):
    merk_attrs = {'id': 'id_merk',
                  'type': 'text',
                  'class': 'form-control',
                  'placeholder': 'MERK'}

    jenis_attrs = {'id': 'id_jenis',
                   'type': 'text',
                   'class': 'form-control',
                   'placeholder': 'JENIS'}

    merk = forms.CharField(label="", required=True, max_length=20,
                           widget=forms.TextInput(attrs=merk_attrs))
    jenis = forms.EmailField(label="", required=True, max_length=50,
                             widget=forms.TextInput(attrs=jenis_attrs))
    stasiun = forms.ChoiceField(choices=render_choices(), label="", initial='',
                                widget=forms.Select(), required=True)
    status = forms.ChoiceField(choices=(('TERSEDIA', 'TERSEDIA'), ('TIDAK TERSEDIA', 'TIDAK TERSEDIA')), label="",
                               initial='', widget=forms.Select(), required=True)
    penyumbang = forms.ChoiceField()

sepeda/views.py
from django.shortcuts import render
from .models import *
from django.core.paginator import Paginator
from registration.check import required_login

content = {}


# Create your views here.
@required_login
def sepeda(request):
    list_sepeda = Sepeda.objects.raw('SELECT * FROM SEPEDA')
    pagination = Paginator(list_sepeda, 6)
    page = request.GET.get('page')
    items = pagination.get_page(page)
    content['items'] = items
    return render(request, 'sepeda/sepeda.html', content)


@required_login
def sortbysepedaASC(request):
    list_sepeda = Sepeda.objects.raw('SELECT * FROM SEPEDA ORDER BY MERK ASC')
    pagination = Paginator(list_sepeda, 6)
    page = request.GET.get('page')
    items = pagination.get_page(page)
    content['items'] = items
    return render(request, 'sepeda/sepeda.html', content)


@required_login
def sortbysepedaDESC(request):
    list_sepeda = Sepeda.objects.raw('SELECT * FROM SEPEDA ORDER BY MERK DESC')
    pagination = Paginator(list_sepeda, 6)
    page = request.GET.get('page')
    items = pagination.get_page(page)
    content['items'] = items
    return render(request, 'sepeda/sepeda.html', content)


@required_login
def register_sepeda(request):
    if request.method == 'POST':
        merk = request.POST['merk']
        jenis = request.POST['jenis']
    list_stasiun = list(Stasiun.objects.raw('SELECT * FROM STASIUN'))
    content['nama_stasiun'] = list_stasiun
    return render(request, 'sepeda/register-sepeda.html', content)


@required_login
def update_sepeda(request, nomor):
    return render(request, 'sepeda/update-sepeda.html')

sepeda/templates/sepeda/register-sepeda.html
{% extends 'base/base.html' %}
{% load static %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="{% static 'sepeda/css/style.css' %}"/>
{% endblock %}

{% block content %}
    <div class="content-info d-flex align-items-center justify-content-between">
        <h5><b>Tambah Sepeda</b></h5>
    </div>
    <form class="form" method="POST">
        <div class="form-group divided-form d-flex justify-content-between">
            <input type="text" name="merk" class="form-control" placeholder="MERK">
            <input type="text" name="jenis" class="form-control" placeholder="JENIS">
        </div>
        <div class="form-group d-flex justify-content-between">
            <div class="dropdown">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                    STATUS
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">TERSEDIA</a>
                    <a class="dropdown-item" href="#">TIDAK TERSEDIA</a>
                </div>
            </div>
            <div class="dropdown">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                    STASIUN
                </button>
                <div class="dropdown-menu">
                    {% for i in nama_stasiun %}
                        <a class="dropdown-item" href="#">{{ i.nama }}</a>
                    {% endfor %}
                </div>
            </div>
            <div class="dropdown">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                    PENYUMBANG
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Link 1</a>
                    <a class="dropdown-item" href="#">Link 2</a>
                    <a class="dropdown-item" href="#">Link 3</a>
                </div>
            </div>
        </div>
        <div class="form-group d-flex justify-content-end">
            <button type="submit" class="btn btn-primary btn-submit">SUBMIT</button>
        </div>
    </form>
{% endblock %}

sepeda/templates/sepeda/sepeda.html
{% extends 'base/base.html' %}
{% load static %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="{% static 'sepeda/css/style.css' %}"/>
{% endblock %}

{% block extrascript %}
    <script src="{% static 'stasiun/js/index.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="content-info d-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center justify-content-between">
            <h5><b>Daftar Sepeda</b></h5>
            {% if request.session.role == 'Petugas' %}
                <a href="{% url 'sepeda:register-sepeda' %}">
                    <button class="btn add-btn-secondary">TAMBAH</button>
                </a>
            {% endif %}
        </div>
        <div class="filter-btn-group d-flex">
            <div class="dropdown">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                    <i class="fas fa-filter"></i> Filter
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Link 1</a>
                    <a class="dropdown-item" href="#">Link 2</a>
                    <a class="dropdown-item" href="#">Link 3</a>
                </div>
            </div>
            <div class="dropdown">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                    <i class="fas fa-sort-amount-down"></i>
                    Sort
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'sepeda:list-sepeda' %}">default</a>
                    <a class="dropdown-item" href="{% url 'sepeda:sort-asc' %}">A to Z</a>
                    <a class="dropdown-item" href="{% url 'sepeda:sort-desc' %}">Z to A</a>
                </div>
            </div>
        </div>
    </div>
    <table class="table table-striped table-hover table-responsive-lg">
        <thead class="thead-light" align="center">
        <tr>
            <th>Nomor</th>
            <th>Merk</th>
            <th>Jenis</th>
            <th>Stasiun</th>
            <th>Status</th>
            <th>Penyumbang</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody align="center">
        {% for item in items %}
            <tr>
                <td>{{ item.nomor }}</td>
                <td>{{ item.merk }}</td>
                <td>{{ item.jenis }}</td>
                <td>{{ item.id_stasiun.nama }}</td>
                {% if item.status %}
                    <td>Tersedia</td>
                {% else %}
                    <td>Tidak Tersedia</td>
                {% endif %}
                <td>{{ item.no_kartu_penyumbang.ktp.nama }}</td>
                {% if request.session.role == 'Petugas' %}
                    <td class="d-flex align-items-center justify-content-center"><a
                            href="{% url 'sepeda:update-sepeda' nomor=item.nomor %}"><i class="fas fa-pen"></i></a><a
                            id="delete-1"
                            onclick="popUpModal()"><i class="fas fa-trash-alt"></i></a></td>
                {% else %}
                    <td>
                        <a href="{% url 'peminjaman:register-peminjaman' %}">
                            <button class="btn btn-primary">PINJAM</button>
                        </a>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <!-- The Modal -->
    <div class="modal fade" id="myModal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

                <!-- Modal body -->
                <div class="modal-body">
                    Apakah benar ingin menghapus sepeda tersebut?
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">TIDAK</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">YA</button>
                </div>
            </div>
        </div>
    </div>
    {% include 'partial/pagination.html' %}
{% endblock %}

sepeda/templates/sepeda/update-sepeda.html
{% extends 'base/base.html' %}
{% load static %}

{% block extracss %}
<link rel="stylesheet" type="text/css" href="{% static 'sepeda/css/style.css' %}" />
{% endblock %}

{% block content %}
<div class="content-info d-flex align-items-center justify-content-between">
    <h5><b>Update Sepeda</b></h5>
</div>
<form class="form">
    <div class="form-group divided-form d-flex justify-content-between">
        <input type="text" class="form-control" placeholder="BMX">
        <input type="text" class="form-control" placeholder="Dewasa">
    </div>
    <div class="form-group d-flex justify-content-between">
        <div class="dropdown">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                TERSEDIA
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">TERSEDIA</a>
                <a class="dropdown-item" href="#">TIDAK TERSEDIA</a>
            </div>
        </div>
        <div class="dropdown">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                Stasiun Depok 1
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Link 1</a>
                <a class="dropdown-item" href="#">Link 2</a>
                <a class="dropdown-item" href="#">Link 3</a>
            </div>
        </div>
        <div class="dropdown">
            <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                -
            </button>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="#">Link 1</a>
                <a class="dropdown-item" href="#">Link 2</a>
                <a class="dropdown-item" href="#">Link 3</a>
            </div>
        </div>
    </div>
    <div class="form-group d-flex justify-content-end">
        <button type="submit" class="btn btn-secondary btn-submit">SUBMIT</button>
    </div>
</form>
{% endblock %}