acara/urls.py
from django.urls import path
from .views import *

app_name = 'acara'
urlpatterns = [
    path('', acara, name="list-acara"),
    path('sortasc/', sortbyacaraASC, name="sort-asc"),
    path('sortdesc/', sortbyacaraDESC, name="sort-desc"),
    path('petugas/register/', register_acara, name="admin-register-acara"),
    path('petugas/update/', update_acara, name="admin-update-acara"),
]

bikesharing/urls.py
from django.contrib import admin
from django.urls import path, include
from registration.views import registration

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('petugas/', include('petugas.urls', namespace='petugas')),
    path('registration/', include('registration.urls', namespace='auth')),
    path('voucher/', include('voucher.urls', namespace='voucher')),
    path('stasiun/', include('stasiun.urls', namespace='stasiun')),
    path('acara/', include('acara.urls', namespace='acara')),
    path('sepeda/', include('sepeda.urls', namespace='sepeda')),
    path('transaksi/', include('transaksi.urls')),
    path('laporan/', include('laporan.urls', namespace='laporan')),
    path('', include('peminjaman.urls', namespace='peminjaman')),
]

voucher/urls.py
from django.urls import path
from voucher import views

app_name = 'voucher'
urlpatterns = [
    path('api-voucher/', views.api_voucher, name='api-voucher'),
    path('createvoucher/', views.createvoucher, name='create-voucher'),
    path('listvoucher/', views.voucher, name='list-voucher'),
    path('hapus-voucher/<str:nama>', views.hapus_voucher, name='hapus-voucher'),
    path('tambah-voucher/', views.tambah_voucher, name='tambah-voucher'),
    path('update-voucher/<str:nama>', views.update_voucher, name='update-voucher'),
    # path('', dashboardvoucher, name="list-voucher"),
]

voucher/models.py
from django.db import models

# Create your models here.

voucher/views.py
from django.shortcuts import render, get_object_or_404
from sepeda.models import *
from django.core.paginator import Paginator
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse, HttpResponseForbidden
from django.db import connection
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
import json

# Create your views here.
content = {}


def createvoucher(request):
    url = "voucher/register-voucher.html"
    return render(request, url)


def listvoucher(request):
    url = "voucher/voucher.html"
    return render(request, url)


def voucher(request):
    list_voucher = Voucher.objects.raw('SELECT * FROM VOUCHER NATURAL JOIN ANGGOTA')
    pagination = Paginator(list_voucher, 10)
    page = request.GET.get('page')
    items = pagination.get_page(page)
    content['items'] = items
    return render(request, 'voucher/voucher.html', content)


def api_voucher(request):
    c = connection.cursor()
    c.execute("SELECT * FROM voucher;")
    result = c.fetchall()
    jsonObject = [dict(zip([key[0] for key in c.description], row))
                  for row in result]
    c.close()
    return HttpResponse(json.dumps({"data": jsonObject}), content_type="application/json")


def tambah_voucher(request):
    if request.method == "POST":
        c = connection.cursor()
        try:
            id_voucher = request.POST.get('id_voucher')
            nama = request.POST.get('nama')
            kategori = request.POST.get('kategori')
            nilai_poin = float(request.POST.get('poin'))
            deskripsi = request.POST.get('deskripsi')
            no_kartu_anggota = request.POST.get('no_kartu_anggota')
            c.execute("INSERT INTO voucher(id_voucher, nama, kategori, nilai_poin, deskripsi, no_kartu_anggota) \
                 VALUES(%s, %s, %s)", [id_voucher, nama, kategori, nilai_poin, deskripsi, no_kartu_anggota])
        finally:
            c.close()
        return HttpResponseRedirect(reverse('level:listvoucher'))
    else:
        return HttpResponseForbidden()


def update_voucher(request, nama):
    url = "voucher/update-voucher.html"
    c = connection.cursor()
    if request.method == "POST":
        try:
            old_nama = nama
            nama = request.POST.get('level')
            kategori = request.POST.get('kategori')
            nilai_poin = float(request.POST.get('poin'))
            deskripsi = request.POST.get('deskripsi')
            c.execute("UPDATE voucher set nama=%s, kategori=%s, nilai_poin=%s,\
                 deskripsi=%s WHERE nama=%s", [nama, kategori, nilai_poin, deskripsi, old_nama])
        finally:
            c.close()
        return HttpResponseRedirect(reverse('level:listvoucher'))

    c.execute("SELECT * FROM voucher WHERE nama=%s",
              [nama])
    result = c.fetchall()
    jsonObject = [dict(zip([key[0] for key in c.description], row))
                  for row in result]
    c.close()
    return render(request, url, {"data": jsonObject})


@csrf_exempt
def hapus_voucher(request, nama):
    c = connection.cursor()
    try:
        c.execute(
            "DELETE FROM voucher WHERE nama=%s", [nama])
    finally:
        c.close()
    return HttpResponseRedirect(reverse('voucher:daftar-voucher'))

voucher/templates/voucher/register-voucher.html
{% extends 'base/base-admin.html' %}
{% load static %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="{% static 'peminjaman/css/style.css' %}"/>
{% endblock %}

{% block content %}
<div class="content-info d-flex align-items-center justify-content-between">
        <h5><b>Tambah  Voucher</b></h5>
</div>
    <form action="{% url 'voucher:tambah-voucher' %}" method="POST">
            {% csrf_token %}
        <div class="form-group">
            <label>Nama</label>
            <input type="text" class="form-control" id="inputName" aria-describedby="emailHelp" placeholder="Enter Name">
        </div>
        <div class="form-group">
            <label>Kategori</label>
            <input type="text" class="form-control" id="inputKategori" placeholder="Enter Kategori">
        </div>
        <div class="form-group">
            <label>Nilai Poin</label>
            <input type="text" class="form-control" id="inputNilaiPoin" placeholder="Enter Nilai Poin">
        </div>
        <div class="form-group">
            <label>Deskripsi</label>
            <input type="text" class="form-control" id="inputDeksripsi" placeholder="Enter Deskripsi">
        </div>
        <div class="form-group">
            <label>Jumlah</label>
            <input type="text" class="form-control" id="inputJumlah" placeholder="Enter Jumlah">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

voucher/templates/voucher/update-voucher.html
{% extends 'base/base.html' %}
{% load static %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style-table.css' %}"/>
{% endblock %}

{% block content %}
    <div class="content-info d-flex align-items-center justify-content-between">
        <h5><b>Update Voucher</b></h5>
    </div>

    <form>
        <div class="form-group">
            <label>Nama</label>
            <input type="text" class="form-control" id="inputName" aria-describedby="emailHelp"
                   placeholder="Voucher Belanja">
        </div>
        <div class="form-group">
            <label>Kategori</label>
            <input type="text" class="form-control" id="inputKategori" placeholder="Belanja">
        </div>
        <div class="form-group">
            <label>Nilai Poin</label>
            <input type="text" class="form-control" id="inputNilaiPoin" placeholder="300">
        </div>
        <div class="form-group">
            <label>Deskripsi</label>
            <input type="text" class="form-control" id="inputDeksripsi" placeholder="Gratis Belanja">
        </div>
        <div class="form-group">
            <label>Jumlah</label>
            <input type="text" class="form-control" id="inputJumlah">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

voucher/templates/voucher/voucher.html
{% extends 'base/base.html' %}
{% load static %}

{% block extracss %}
    <link rel="stylesheet" type="text/css" href="{% static 'voucher/css/style.css' %}"/>
{% endblock %}

{% block extrascript %}
    <script src="{% static 'stasiun/js/index.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="content-info d-flex align-items-center justify-content-between">
        <h5><b>Daftar Voucher</b></h5>
        <div class="filter-btn-group d-flex">
            <div class="dropdown">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                    <i class="fas fa-filter"></i> Filter
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Link 1</a>
                    <a class="dropdown-item" href="#">Link 2</a>
                    <a class="dropdown-item" href="#">Link 3</a>
                </div>
            </div>
            <div class="dropdown">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown">
                    <i class="fas fa-sort-amount-down"></i>
                    Sort
                </button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Link 1</a>
                    <a class="dropdown-item" href="#">Link 2</a>
                    <a class="dropdown-item" href="#">Link 3</a>
                </div>
            </div>
        </div>
    </div>
    <table id="id-table" class="table table-striped table-hover table-responsive-lg">
        <thead class="thead-light" align="center">
        <tr>
            <th>ID Voucher</th>
            <th>Nama</th>
            <th>Kategori</th>
            <th>Nilai Poin</th>
            <th>Deskripsi</th>
            <th>Diklaim Oleh</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody align="center">
        {% for item in items %}
            <tr>
                <td>{{ item.id_voucher }}</td>
                <td>{{ item.nama }}</td>
                <td>{{ item.kategori }}</td>
                <td>{{ item.nilai_poin }}</td>
                <td>{{ item.deskripsi }}</td>
                <td>-</td>
                {% if request.session.role == 'Petugas' %}
                    <td class="d-flex align-items-center justify-content-center"><a
                            href="{% url 'voucher:update-voucher' nama=item.id_voucher %}"><i
                            class="fas fa-pen"></i></a><a
                            id="delete-1"
                            onclick="popUpModal()"><i class="fas fa-trash-alt"></i></a></td>
                {% else %}
                    <td>
                        <button type="button" class="btn btn-primary btn-sm">KLAIM</button>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <!-- The Modal -->
    <div class="modal fade" id="myModal">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

                <!-- Modal body -->
                <div class="modal-body">
                    Apakah benar ingin menghapus sepeda tersebut?
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">TIDAK</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">YA</button>
                </div>
            </div>
        </div>
    </div>
    {% include 'partial/pagination.html' %}
{% endblock %}